name: Continuous Integration

on:
  push:
    branches:
      - main
      - master
  pull_request:
  schedule:
    - cron: '30 7 * * *' # weekly, at 7:30am

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 9.2.0
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm
      - name: Install Dependencies
        run: pnpm install
      - name: Lint
        run: pnpm run lint

  tests:
    name: "QUnit Tests"
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 9.2.0
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - name: Install Dependencies
        run: pnpm install
      - name: Run Tests
        run: pnpm test

  coverage:
    name: Upload Code Coverage
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: tests
    steps:
      - uses: actions/checkout@v4
      - name: Download Coverage Report
        uses: actions/download-artifact@v4
        with:
          name: coverage-output
      - run: ls -lh coverage.xml
      - name: Upload to CodeClimate
        uses: paambaati/codeclimate-action@v6.0.0
        env:
          CC_TEST_REPORTER_ID: b2dde9b9e0d2527871c0676385628df9f9778b2dd778f1ccb1425aaa03960a6f
        with:
          coverageLocations:
            coverage.xml:clover

