name: Continuous Integration

on:
  push:
    branches:
      - main
      - master
  pull_request:
  schedule:
    - cron: '30 7 * * *' # weekly, at 7:30am

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 9.1.1
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm
      - name: Install Dependencies
        run: pnpm install
      - name: Lint
        run: pnpm run lint

  test:
    name: "QUnit Tests"
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 9.1.1
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm
      - name: Install Dependencies
        run: pnpm install
      - name: Run Tests
        run: pnpm test
